service: finzenapirest

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-west-2
  architecture: arm64 # Cambia según tu preferencia
  # stage: ${opt:stage, 'dev'}
  stage: production
  memorySize: 3008 # Tamaño de memoria en MB (máximo permitido)
  logRetentionInDays: 1 # Retención de logs en días
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

plugins:
  - serverless-jetpack
  - serverless-offline
