service: finzenapirest

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  # stage: ${opt:stage, 'dev'}
  stage: production
  memorySize: 2048 # Tamaño de memoria en MB (máximo permitido)
  logRetentionInDays: 1 # Retención de logs en días
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      
plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin
