service: finzenapirest

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  stage: production
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 15


functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    package:
      individually: true
      include:
        - '!generated/prisma/query_engine-windows.dll.node'
        - '!generated/prisma/query_engine-windows.dll.node.tmp52124'
        - '!generated/prisma/schema.prisma'
        - '!generated.zip'
        - '!node_modules/prisma/**'
        - '!node_modules/@prisma/**'
        - '!node_modules/@angular-devkit/**'


      
plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin
