service: finzenapirest

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-west-2
  architecture: arm64 # Cambia según tu preferencia
  # stage: ${opt:stage, 'dev'}
  stage: production
  memorySize: 3008 # Tamaño de memoria en MB (máximo permitido)
  logRetentionInDays: 1 # Retención de logs en días
  timeout: 15
  environment:
    DATABASE_URL: ${env:DATABASE_URL} # URL de conexión a la base de datos
    API_KEY: ${env:API_KEY} # Clave de autenticación
    FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${env:FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
    FIREBASE_AUTH_URI: ${env:FIREBASE_AUTH_URI}
    FIREBASE_CLIENT_EMAIL: ${env:FIREBASE_CLIENT_EMAIL}
    FIREBASE_CLIENT_ID: ${env:FIREBASE_CLIENT_ID}
    FIREBASE_CLIENT_X509_CERT_URL: ${env:FIREBASE_CLIENT_X509_CERT_URL}
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}
    FIREBASE_PRIVATE_KEY_ID: ${env:FIREBASE_PRIVATE_KEY_ID}
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_TOKEN_URI: ${env:FIREBASE_TOKEN_URI}
    FIREBASE_TYPE: ${env:FIREBASE_TYPE}
    FIREBASE_UNIVERSE_DOMAIN: ${env:FIREBASE_UNIVERSE_DOMAIN}
    JWT_SECRET: ${env:JWT_SECRET} # Secreto para firmar JWT



functions:
  api:
    handler: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin
